
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcjdeqfqbucfterqzglp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jamRlcWZxYnVjZnRlcnF6Z2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNzIzMjcsImV4cCI6MjA2NDc0ODMyN30.rg_2g5w9TidNCnTBsVtF2WTYZOXdgfPXSiIgnDJeTcw";

console.log('Supabase client initializing with URL:', SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

console.log('Supabase client initialized successfully');
