
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcjdeqfqbucfterqzglp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jamRlcWZxYnVjZnRlcnF6Z2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNzIzMjcsImV4cCI6MjA2NDc0ODMyN30.rg_2g5w9TidNCnTBsVtF2WTYZOXdgfPXSiIgnDJeTcw";

console.log('Supabase client initializing with URL:', SUPABASE_URL);
console.log('Supabase key (first 20 chars):', SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...');

// Test basic connectivity
const testConnectivity = async () => {
  try {
    console.log('Testing connectivity to Supabase...');
    const response = await fetch(`${SUPABASE_URL}/rest/v1/`, {
      method: 'GET',
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY,
        'Authorization': `Bearer ${SUPABASE_PUBLISHABLE_KEY}`
      }
    });
    console.log('Connectivity test response status:', response.status);
    console.log('Connectivity test response headers:', Object.fromEntries(response.headers.entries()));
  } catch (error) {
    console.error('Connectivity test failed:', error);
  }
};

// Run connectivity test
testConnectivity();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.localStorage,
    persistSession: true,
    autoRefreshToken: true,
    debug: true
  },
  global: {
    headers: {
      'X-Client-Info': 'construction-management-app'
    }
  }
});

console.log('Supabase client initialized successfully');

// Test the client
supabase.auth.getSession().then(({ data, error }) => {
  console.log('Initial session test:', { data, error });
}).catch(error => {
  console.error('Initial session test failed:', error);
});
